[package]
name = "simple-ica"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
host = ["dep:osmo-bindings"]

[dependencies]
cosmwasm-std = { version = "1.1", features = ["ibc3"] }
schemars = "0.8.1"
osmosis-std = "0.12.0"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
osmo-bindings = { git = "https://github.com/osmosis-labs/bindings",optional = true}
thiserror = { version = "1.0.23" }
client-osmo-bindings = { package = "osmo-bindings", git = "https://github.com/OracleDAODAO/osmo-bindings-client"}

[dev-dependencies]
cosmwasm-schema = { version = "1.1" }
